/* Generated by AN DISI Unibo */ 
package it.unibo.sender

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Sender ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 var emitEvents = true  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("sending msg1")
						forward("msg1", "msg1(hello(world))" ,"demo0" ) 
						delay(300) 
						println("sending msg1 again")
						forward("msg1", "msg1(2)" ,"demo0" ) 
						delay(300) 
						println("sending msg2 ")
						forward("msg2", "msg2(1)" ,"demo0" ) 
						delay(300) 
						if(  emitEvents  
						 ){println("emit alarm ")
						emit("alarm", "alarm(fire)" ) 
						}
					}
				}	 
			}
		}
}
