/* Generated by AN DISI Unibo */ 
package it.unibo.robotappl1

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Robotappl1 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "activate"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 val Inmapname   = "map2019.txt"  
			   var PathTodo    =  ""  
			   var Mapp        = "|r, 1, 1, 1, 1, 1, 1,"
		/* |r, 1, 1, 1, 1, 1, 1, 
		|1, 1, 1, 1, 1, 1, 1, 
		|1, 1, X, 1, 1, 1, 1,  
		|1, 1, 0, 1, 1, 1, 1, 
		|1, 1, 0, 1, 1, 1, 1, 
		|X, X, 0, X, X, X, X,*/
		return { //this:ActionBasciFsm
				state("activate") { //this:State
					action { //it:State
						unibo.kotlin.planner22Util.createRoomMapFromTextfile( "$Inmapname"  )
						unibo.kotlin.planner22Util.initAI(  )
						println("uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu")
						unibo.kotlin.planner22Util.showCurrentRobotState(  )
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						unibo.kotlin.planner22Util.setGoal( 1, 1  )
						 PathTodo = unibo.kotlin.planner22Util.doPlan().toString() 
						println("Azioni pianificate: $PathTodo")
						request("dopath", "dopath($PathTodo,map($Mapp))" ,"pathexec" )  
					}
					 transition(edgeName="t00",targetState="pathok",cond=whenReply("dopathdone"))
					transition(edgeName="t01",targetState="pathko",cond=whenReply("dopathfail"))
				}	 
				state("pathok") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
					}
				}	 
				state("pathko") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						unibo.kotlin.planner22Util.showMap(  )
						unibo.kotlin.planner22Util.showCurrentRobotState(  )
					}
				}	 
				state("end") { //this:State
					action { //it:State
						println("BYE")
					}
				}	 
			}
		}
}
