/* Generated by AN DISI Unibo */ 
package it.unibo.datahandler

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Datahandler ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						forward("start", "start(do)" ,"sonargen" ) 
					}
					 transition(edgeName="t00",targetState="handleSonarevent",cond=whenEvent("sonarrobot"))
				}	 
				state("handleSonarevent") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						stateTimer = TimerActor("timer_handleSonarevent", 
							scope, context!!, "local_tout_datahandler_handleSonarevent", 1000.toLong() )
					}
					 transition(edgeName="t01",targetState="end",cond=whenTimeout("local_tout_datahandler_handleSonarevent"))   
					transition(edgeName="t02",targetState="handleSonarevent",cond=whenEvent("sonarrobot"))
				}	 
				state("end") { //this:State
					action { //it:State
						println("BYE")
					}
				}	 
			}
		}
}
