/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Code Run Simple</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.qactork.CodeRunSimple#getBitem <em>Bitem</em>}</li>
 * </ul>
 *
 * @see it.unibo.qactork.QactorkPackage#getCodeRunSimple()
 * @model
 * @generated
 */
public interface CodeRunSimple extends CodeRun
{
  /**
   * Returns the value of the '<em><b>Bitem</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bitem</em>' attribute.
   * @see #setBitem(String)
   * @see it.unibo.qactork.QactorkPackage#getCodeRunSimple_Bitem()
   * @model
   * @generated
   */
  String getBitem();

  /**
   * Sets the value of the '{@link it.unibo.qactork.CodeRunSimple#getBitem <em>Bitem</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bitem</em>' attribute.
   * @see #getBitem()
   * @generated
   */
  void setBitem(String value);

} // CodeRunSimple
