/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delay Var</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.qactork.DelayVar#getRefvar <em>Refvar</em>}</li>
 * </ul>
 *
 * @see it.unibo.qactork.QactorkPackage#getDelayVar()
 * @model
 * @generated
 */
public interface DelayVar extends Delay
{
  /**
   * Returns the value of the '<em><b>Refvar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refvar</em>' containment reference.
   * @see #setRefvar(Variable)
   * @see it.unibo.qactork.QactorkPackage#getDelayVar_Refvar()
   * @model containment="true"
   * @generated
   */
  Variable getRefvar();

  /**
   * Sets the value of the '{@link it.unibo.qactork.DelayVar#getRefvar <em>Refvar</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refvar</em>' containment reference.
   * @see #getRefvar()
   * @generated
   */
  void setRefvar(Variable value);

} // DelayVar
