/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delay Int</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.qactork.DelayInt#getTime <em>Time</em>}</li>
 * </ul>
 *
 * @see it.unibo.qactork.QactorkPackage#getDelayInt()
 * @model
 * @generated
 */
public interface DelayInt extends Delay
{
  /**
   * Returns the value of the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' attribute.
   * @see #setTime(int)
   * @see it.unibo.qactork.QactorkPackage#getDelayInt_Time()
   * @model
   * @generated
   */
  int getTime();

  /**
   * Sets the value of the '{@link it.unibo.qactork.DelayInt#getTime <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' attribute.
   * @see #getTime()
   * @generated
   */
  void setTime(int value);

} // DelayInt
