/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>End Actor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.qactork.EndActor#getArg <em>Arg</em>}</li>
 * </ul>
 *
 * @see it.unibo.qactork.QactorkPackage#getEndActor()
 * @model
 * @generated
 */
public interface EndActor extends StateAction
{
  /**
   * Returns the value of the '<em><b>Arg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg</em>' attribute.
   * @see #setArg(int)
   * @see it.unibo.qactork.QactorkPackage#getEndActor_Arg()
   * @model
   * @generated
   */
  int getArg();

  /**
   * Sets the value of the '{@link it.unibo.qactork.EndActor#getArg <em>Arg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg</em>' attribute.
   * @see #getArg()
   * @generated
   */
  void setArg(int value);

} // EndActor
