/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.qactork.Exec#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see it.unibo.qactork.QactorkPackage#getExec()
 * @model
 * @generated
 */
public interface Exec extends StateAction
{
  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see #setAction(String)
   * @see it.unibo.qactork.QactorkPackage#getExec_Action()
   * @model
   * @generated
   */
  String getAction();

  /**
   * Sets the value of the '{@link it.unibo.qactork.Exec#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see #getAction()
   * @generated
   */
  void setAction(String value);

} // Exec
