/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.qactork.InputTransition#getGuard <em>Guard</em>}</li>
 *   <li>{@link it.unibo.qactork.InputTransition#getTargetState <em>Target State</em>}</li>
 * </ul>
 *
 * @see it.unibo.qactork.QactorkPackage#getInputTransition()
 * @model
 * @generated
 */
public interface InputTransition extends EObject
{
  /**
   * Returns the value of the '<em><b>Guard</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guard</em>' containment reference.
   * @see #setGuard(AnyAction)
   * @see it.unibo.qactork.QactorkPackage#getInputTransition_Guard()
   * @model containment="true"
   * @generated
   */
  AnyAction getGuard();

  /**
   * Sets the value of the '{@link it.unibo.qactork.InputTransition#getGuard <em>Guard</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Guard</em>' containment reference.
   * @see #getGuard()
   * @generated
   */
  void setGuard(AnyAction value);

  /**
   * Returns the value of the '<em><b>Target State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target State</em>' reference.
   * @see #setTargetState(State)
   * @see it.unibo.qactork.QactorkPackage#getInputTransition_TargetState()
   * @model
   * @generated
   */
  State getTargetState();

  /**
   * Sets the value of the '{@link it.unibo.qactork.InputTransition#getTargetState <em>Target State</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target State</em>' reference.
   * @see #getTargetState()
   * @generated
   */
  void setTargetState(State value);

} // InputTransition
