/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Invitation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.qactork.QactorkPackage#getInvitation()
 * @model
 * @generated
 */
public interface Invitation extends OutInMessage
{
} // Invitation
