/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Msg Cond</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.qactork.MsgCond#getMessage <em>Message</em>}</li>
 *   <li>{@link it.unibo.qactork.MsgCond#getMsg <em>Msg</em>}</li>
 *   <li>{@link it.unibo.qactork.MsgCond#getCondactions <em>Condactions</em>}</li>
 *   <li>{@link it.unibo.qactork.MsgCond#getIfnot <em>Ifnot</em>}</li>
 * </ul>
 *
 * @see it.unibo.qactork.QactorkPackage#getMsgCond()
 * @model
 * @generated
 */
public interface MsgCond extends StateAction
{
  /**
   * Returns the value of the '<em><b>Message</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' reference.
   * @see #setMessage(Message)
   * @see it.unibo.qactork.QactorkPackage#getMsgCond_Message()
   * @model
   * @generated
   */
  Message getMessage();

  /**
   * Sets the value of the '{@link it.unibo.qactork.MsgCond#getMessage <em>Message</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' reference.
   * @see #getMessage()
   * @generated
   */
  void setMessage(Message value);

  /**
   * Returns the value of the '<em><b>Msg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Msg</em>' containment reference.
   * @see #setMsg(PHead)
   * @see it.unibo.qactork.QactorkPackage#getMsgCond_Msg()
   * @model containment="true"
   * @generated
   */
  PHead getMsg();

  /**
   * Sets the value of the '{@link it.unibo.qactork.MsgCond#getMsg <em>Msg</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Msg</em>' containment reference.
   * @see #getMsg()
   * @generated
   */
  void setMsg(PHead value);

  /**
   * Returns the value of the '<em><b>Condactions</b></em>' containment reference list.
   * The list contents are of type {@link it.unibo.qactork.StateAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condactions</em>' containment reference list.
   * @see it.unibo.qactork.QactorkPackage#getMsgCond_Condactions()
   * @model containment="true"
   * @generated
   */
  EList<StateAction> getCondactions();

  /**
   * Returns the value of the '<em><b>Ifnot</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ifnot</em>' containment reference.
   * @see #setIfnot(NoMsgCond)
   * @see it.unibo.qactork.QactorkPackage#getMsgCond_Ifnot()
   * @model containment="true"
   * @generated
   */
  NoMsgCond getIfnot();

  /**
   * Sets the value of the '{@link it.unibo.qactork.MsgCond#getIfnot <em>Ifnot</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ifnot</em>' containment reference.
   * @see #getIfnot()
   * @generated
   */
  void setIfnot(NoMsgCond value);

} // MsgCond
