/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PAtom</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.qactork.QactorkPackage#getPAtom()
 * @model
 * @generated
 */
public interface PAtom extends PHead
{
} // PAtom
