/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PAtom Num</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.qactork.PAtomNum#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see it.unibo.qactork.QactorkPackage#getPAtomNum()
 * @model
 * @generated
 */
public interface PAtomNum extends PAtom
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(int)
   * @see it.unibo.qactork.QactorkPackage#getPAtomNum_Val()
   * @model
   * @generated
   */
  int getVal();

  /**
   * Sets the value of the '{@link it.unibo.qactork.PAtomNum#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(int value);

} // PAtomNum
