/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>QActor External</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.qactork.QactorkPackage#getQActorExternal()
 * @model
 * @generated
 */
public interface QActorExternal extends QActorDeclaration
{
} // QActorExternal
