/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Request Trans Switch</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.qactork.RequestTransSwitch#getMessage <em>Message</em>}</li>
 * </ul>
 *
 * @see it.unibo.qactork.QactorkPackage#getRequestTransSwitch()
 * @model
 * @generated
 */
public interface RequestTransSwitch extends InputTransition
{
  /**
   * Returns the value of the '<em><b>Message</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' reference.
   * @see #setMessage(Request)
   * @see it.unibo.qactork.QactorkPackage#getRequestTransSwitch_Message()
   * @model
   * @generated
   */
  Request getMessage();

  /**
   * Sets the value of the '{@link it.unibo.qactork.RequestTransSwitch#getMessage <em>Message</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' reference.
   * @see #getMessage()
   * @generated
   */
  void setMessage(Request value);

} // RequestTransSwitch
