/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Signal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.qactork.QactorkPackage#getSignal()
 * @model
 * @generated
 */
public interface Signal extends OutOnlyMessage
{
} // Signal
