/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Timeout Int</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.qactork.TimeoutInt#getMsec <em>Msec</em>}</li>
 * </ul>
 *
 * @see it.unibo.qactork.QactorkPackage#getTimeoutInt()
 * @model
 * @generated
 */
public interface TimeoutInt extends Timeout
{
  /**
   * Returns the value of the '<em><b>Msec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Msec</em>' attribute.
   * @see #setMsec(int)
   * @see it.unibo.qactork.QactorkPackage#getTimeoutInt_Msec()
   * @model
   * @generated
   */
  int getMsec();

  /**
   * Sets the value of the '{@link it.unibo.qactork.TimeoutInt#getMsec <em>Msec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Msec</em>' attribute.
   * @see #getMsec()
   * @generated
   */
  void setMsec(int value);

} // TimeoutInt
