/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.qactork.QactorkPackage#getTransition()
 * @model
 * @generated
 */
public interface Transition extends EObject
{
} // Transition
