/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Update Resource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.qactork.UpdateResource#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see it.unibo.qactork.QactorkPackage#getUpdateResource()
 * @model
 * @generated
 */
public interface UpdateResource extends StateAction
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' containment reference.
   * @see #setVal(AnyAction)
   * @see it.unibo.qactork.QactorkPackage#getUpdateResource_Val()
   * @model containment="true"
   * @generated
   */
  AnyAction getVal();

  /**
   * Sets the value of the '{@link it.unibo.qactork.UpdateResource#getVal <em>Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' containment reference.
   * @see #getVal()
   * @generated
   */
  void setVal(AnyAction value);

} // UpdateResource
