/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork.impl;

import it.unibo.qactork.OutInMessage;
import it.unibo.qactork.QactorkPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Out In Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OutInMessageImpl extends MessageImpl implements OutInMessage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OutInMessageImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QactorkPackage.Literals.OUT_IN_MESSAGE;
  }

} //OutInMessageImpl
