/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork.impl;

import it.unibo.qactork.PrintCurMsg;
import it.unibo.qactork.QactorkPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Print Cur Msg</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PrintCurMsgImpl extends StateActionImpl implements PrintCurMsg
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrintCurMsgImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QactorkPackage.Literals.PRINT_CUR_MSG;
  }

} //PrintCurMsgImpl
