/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork.impl;

import it.unibo.qactork.QActorExternal;
import it.unibo.qactork.QactorkPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>QActor External</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class QActorExternalImpl extends QActorDeclarationImpl implements QActorExternal
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QActorExternalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QactorkPackage.Literals.QACTOR_EXTERNAL;
  }

} //QActorExternalImpl
