/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork.impl;

import it.unibo.qactork.QActorSystem;
import it.unibo.qactork.QActorSystemSpec;
import it.unibo.qactork.QactorkPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>QActor System</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.qactork.impl.QActorSystemImpl#isTrace <em>Trace</em>}</li>
 *   <li>{@link it.unibo.qactork.impl.QActorSystemImpl#isLogmsg <em>Logmsg</em>}</li>
 *   <li>{@link it.unibo.qactork.impl.QActorSystemImpl#getSpec <em>Spec</em>}</li>
 * </ul>
 *
 * @generated
 */
public class QActorSystemImpl extends MinimalEObjectImpl.Container implements QActorSystem
{
  /**
   * The default value of the '{@link #isTrace() <em>Trace</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isTrace()
   * @generated
   * @ordered
   */
  protected static final boolean TRACE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isTrace() <em>Trace</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isTrace()
   * @generated
   * @ordered
   */
  protected boolean trace = TRACE_EDEFAULT;

  /**
   * The default value of the '{@link #isLogmsg() <em>Logmsg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isLogmsg()
   * @generated
   * @ordered
   */
  protected static final boolean LOGMSG_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isLogmsg() <em>Logmsg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isLogmsg()
   * @generated
   * @ordered
   */
  protected boolean logmsg = LOGMSG_EDEFAULT;

  /**
   * The cached value of the '{@link #getSpec() <em>Spec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpec()
   * @generated
   * @ordered
   */
  protected QActorSystemSpec spec;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QActorSystemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QactorkPackage.Literals.QACTOR_SYSTEM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isTrace()
  {
    return trace;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTrace(boolean newTrace)
  {
    boolean oldTrace = trace;
    trace = newTrace;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QactorkPackage.QACTOR_SYSTEM__TRACE, oldTrace, trace));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isLogmsg()
  {
    return logmsg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLogmsg(boolean newLogmsg)
  {
    boolean oldLogmsg = logmsg;
    logmsg = newLogmsg;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QactorkPackage.QACTOR_SYSTEM__LOGMSG, oldLogmsg, logmsg));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QActorSystemSpec getSpec()
  {
    return spec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSpec(QActorSystemSpec newSpec, NotificationChain msgs)
  {
    QActorSystemSpec oldSpec = spec;
    spec = newSpec;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QactorkPackage.QACTOR_SYSTEM__SPEC, oldSpec, newSpec);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSpec(QActorSystemSpec newSpec)
  {
    if (newSpec != spec)
    {
      NotificationChain msgs = null;
      if (spec != null)
        msgs = ((InternalEObject)spec).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QactorkPackage.QACTOR_SYSTEM__SPEC, null, msgs);
      if (newSpec != null)
        msgs = ((InternalEObject)newSpec).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QactorkPackage.QACTOR_SYSTEM__SPEC, null, msgs);
      msgs = basicSetSpec(newSpec, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QactorkPackage.QACTOR_SYSTEM__SPEC, newSpec, newSpec));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QactorkPackage.QACTOR_SYSTEM__SPEC:
        return basicSetSpec(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QactorkPackage.QACTOR_SYSTEM__TRACE:
        return isTrace();
      case QactorkPackage.QACTOR_SYSTEM__LOGMSG:
        return isLogmsg();
      case QactorkPackage.QACTOR_SYSTEM__SPEC:
        return getSpec();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QactorkPackage.QACTOR_SYSTEM__TRACE:
        setTrace((Boolean)newValue);
        return;
      case QactorkPackage.QACTOR_SYSTEM__LOGMSG:
        setLogmsg((Boolean)newValue);
        return;
      case QactorkPackage.QACTOR_SYSTEM__SPEC:
        setSpec((QActorSystemSpec)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QactorkPackage.QACTOR_SYSTEM__TRACE:
        setTrace(TRACE_EDEFAULT);
        return;
      case QactorkPackage.QACTOR_SYSTEM__LOGMSG:
        setLogmsg(LOGMSG_EDEFAULT);
        return;
      case QactorkPackage.QACTOR_SYSTEM__SPEC:
        setSpec((QActorSystemSpec)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QactorkPackage.QACTOR_SYSTEM__TRACE:
        return trace != TRACE_EDEFAULT;
      case QactorkPackage.QACTOR_SYSTEM__LOGMSG:
        return logmsg != LOGMSG_EDEFAULT;
      case QactorkPackage.QACTOR_SYSTEM__SPEC:
        return spec != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (trace: ");
    result.append(trace);
    result.append(", logmsg: ");
    result.append(logmsg);
    result.append(')');
    return result.toString();
  }

} //QActorSystemImpl
