/**
 * generated by Xtext 2.22.0
 */
package it.unibo.qactork.impl;

import it.unibo.qactork.QactorkPackage;
import it.unibo.qactork.TimeoutVarRef;
import it.unibo.qactork.VarRef;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Timeout Var Ref</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.unibo.qactork.impl.TimeoutVarRefImpl#getRefvar <em>Refvar</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TimeoutVarRefImpl extends TimeoutImpl implements TimeoutVarRef
{
  /**
   * The cached value of the '{@link #getRefvar() <em>Refvar</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRefvar()
   * @generated
   * @ordered
   */
  protected VarRef refvar;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TimeoutVarRefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QactorkPackage.Literals.TIMEOUT_VAR_REF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VarRef getRefvar()
  {
    return refvar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRefvar(VarRef newRefvar, NotificationChain msgs)
  {
    VarRef oldRefvar = refvar;
    refvar = newRefvar;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, QactorkPackage.TIMEOUT_VAR_REF__REFVAR, oldRefvar, newRefvar);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRefvar(VarRef newRefvar)
  {
    if (newRefvar != refvar)
    {
      NotificationChain msgs = null;
      if (refvar != null)
        msgs = ((InternalEObject)refvar).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - QactorkPackage.TIMEOUT_VAR_REF__REFVAR, null, msgs);
      if (newRefvar != null)
        msgs = ((InternalEObject)newRefvar).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - QactorkPackage.TIMEOUT_VAR_REF__REFVAR, null, msgs);
      msgs = basicSetRefvar(newRefvar, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QactorkPackage.TIMEOUT_VAR_REF__REFVAR, newRefvar, newRefvar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case QactorkPackage.TIMEOUT_VAR_REF__REFVAR:
        return basicSetRefvar(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QactorkPackage.TIMEOUT_VAR_REF__REFVAR:
        return getRefvar();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QactorkPackage.TIMEOUT_VAR_REF__REFVAR:
        setRefvar((VarRef)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QactorkPackage.TIMEOUT_VAR_REF__REFVAR:
        setRefvar((VarRef)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QactorkPackage.TIMEOUT_VAR_REF__REFVAR:
        return refvar != null;
    }
    return super.eIsSet(featureID);
  }

} //TimeoutVarRefImpl
