/*
*  Generated by AN Unibo
*/
package it.unibo.comm2022.udp;

import java.net.DatagramSocket;
import java.net.InetAddress;

import it.unibo.comm2022.interfaces.IUdpConnection;
import it.unibo.comm2022.utils.ColorsOut;

public class SocketUdpSupport  implements IUdpConnection{
 	private boolean debug = false;
	private DatagramSocket socket;

	
	public  DatagramSocket connectAsReceiver(int portNum) throws Exception {
	try{
 		println( "connectAsReceiver on port " + portNum );
		socket = new DatagramSocket( portNum );		
		return socket;		
	}catch( Exception e ){
		println("connectAsReceiver ERROR  *** " + portNum + " " + e.getMessage() );
		throw e;
	}
	}
	
	

	public DatagramSocket connectAsClient(String hostName,  int portNum) throws Exception {
		ColorsOut.outappl("SocketUdpSupport |  connectAsClient to port:"  + portNum, ColorsOut.BLUE );	
 		InetAddress ia = InetAddress.getByName(hostName);
		DatagramSocket socket;
 		socket = new DatagramSocket(  ); //if no arg => anonymous
// 		socket = new DatagramSocket( portNum ); //if no arg => anonymous
		ColorsOut.outappl("SocketUdpSupport |  connected to port " + portNum + " using " +socket.getLocalPort(), ColorsOut.BLUE );	
		return socket;
	}	

	
	public void closeConnection(DatagramSocket socket){
		println( "CLOSING" );
		socket.close();
	}
	
	protected  void println( String msg){
		 if( debug ) 
			 doprintln("		+++ SocketUdpSupport |"   + " " + msg  );
	}

	protected  void doprintln( String msg){
		ColorsOut.out( msg  );		
	}



 }
