/* Generated by AN DISI Unibo */ 
package it.unibo.sonarqak22

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Sonarqak22 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 lateinit var Sonar : `it.unibo`.radarSystem22.domain.interfaces.ISonar  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						
									`it.unibo`.radarSystem22.domain.utils.DomainSystemConfig.simulation   	= true;			
									`it.unibo`.radarSystem22.domain.utils.DomainSystemConfig.tracing      	= true;		
									`it.unibo`.radarSystem22.domain.utils.DomainSystemConfig.sonarDelay   	= 200;
						//			`it.unibo`.radarSystem22.domain.utils.CommSystemConfig.tracing        	= false;	
						             Sonar = `it.unibo`.radarSystem22.domain.DeviceFactory.createSonar()	
						             println(Sonar)	
					}
					 transition(edgeName="t00",targetState="activateTheSonar",cond=whenDispatch("sonaractivate"))
					transition(edgeName="t01",targetState="deactivateTheSonar",cond=whenDispatch("sonardeactivate"))
				}	 
				state("activateTheSonar") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if(   `it.unibo`.radarSystem22.domain.utils.DomainSystemConfig.simulation  
						 ){ Sonar.activate() 
						println(" SonarMock| sonarSetUp done ")
						}
					}
					 transition( edgeName="goto",targetState="end", cond=doswitch() )
				}	 
				state("deactivateTheSonar") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
					}
				}	 
				state("end") { //this:State
					action { //it:State
						delay(3000) 
						println("sonarqak22 BYE")
						 System.exit(0)  
					}
				}	 
			}
		}
}
