/* Generated by AN DISI Unibo */ 
package it.unibo.appl

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Appl ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("appl | start")
						solve("consult('sysRules.pl')","") //set resVar	
						solve("consult('applRulesKb.pl')","") //set resVar	
						solve("led(X)","") //set resVar	
						 val x = getCurSol("X").toString() 
						 		   println( "appl | led $x" )
					}
					 transition( edgeName="goto",targetState="waitwork", cond=doswitch() )
				}	 
				state("waitwork") { //this:State
					action { //it:State
					}
					 transition(edgeName="t03",targetState="work",cond=whenEvent("local_appl"))
				}	 
				state("work") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("job(X)"), Term.createTerm("job(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								  val D  = applsupport.getSonarDistance( payloadArg(0) )
												solve( "modifyResource($D,R)" )
												//println( currentSolution )
												val DoResource = getCurSol("R")
												println( "DoResource=$DoResource" )
												
												solve( "modifyLed($D,20,RT)" )
												val DoLed  = getCurSol("RT")
								if(  DoResource =="ok"  
								 ){emit("local_update", "value(sonarrobot($D))" ) 
								}
								if(  DoLed      =="ok"  
								 ){emit("local_update", "value(led(on))" ) 
								}
								else
								 {emit("local_update", "value(led(off))" ) 
								 }
						}
					}
					 transition( edgeName="goto",targetState="waitwork", cond=doswitch() )
				}	 
			}
		}
}
