/* Generated by AN DISI Unibo */ 
package it.unibo.blsonoff

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Blsonoff ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
				var odd         = true
				var toutCounter = 0
				val maxCounter  = 5
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						stateTimer = TimerActor("timer_work", 
							scope, context!!, "local_tout_blsonoff_work", 1000.toLong() )
					}
					 transition(edgeName="t00",targetState="tout",cond=whenTimeout("local_tout_blsonoff_work"))   
					transition(edgeName="t01",targetState="switchLed",cond=whenEvent("local_buttonCmd"))
					transition(edgeName="t02",targetState="endOfWork",cond=whenEvent("end"))
				}	 
				state("switchLed") { //this:State
					action { //it:State
						if(  odd  
						 ){updateResourceRep( "ledCmdOn"  
						)
						forward("ledCmd", "ledCmd(on)" ,"led" ) 
						}
						else
						 {updateResourceRep( "ledCmdOff"  
						 )
						 forward("ledCmd", "ledCmd(off)" ,"led" ) 
						 }
						 odd = !odd  
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("tout") { //this:State
					action { //it:State
						 toutCounter++  
						emit("local_buttonCmd", "local_buttonCmd(0)" ) 
					}
					 transition( edgeName="goto",targetState="switchLed", cond=doswitchGuarded({ toutCounter < maxCounter  
					}) )
					transition( edgeName="goto",targetState="endOfWork", cond=doswitchGuarded({! ( toutCounter < maxCounter  
					) }) )
				}	 
				state("endOfWork") { //this:State
					action { //it:State
						println("blsonoff BYE")
						terminate(0)
					}
				}	 
			}
		}
}
