/*
 * generated by Xtext 2.22.0
 */
package it.unibo.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQactorkScopeProvider extends DelegatingScopeProvider {
}
