/* Generated by AN DISI Unibo */ 
package it.unibo.ctxtesta
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "demo0g.pl", "sysRules.pl","ctxtesta"
	)
}

